FROM user:base-d

ARG THISUSER
ARG HOMEDIR=/home
ARG USERHOME=$HOMEDIR/$THISUSER
# # FROM therest AS python310
# RUN sudo add-apt-repository ppa:deadsnakes/ppa -y\
#   && sudo apt-get install -y python3.10\
#   && sudo apt-get install -y python3.10-venv
# RUN sudo apt-get install python3-pip -yq\
#   && python3.10 -m pip install --upgrade pip
# RUN sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 100

# RUN sudo add-apt-repository ppa:deadsnakes/ppa -y\
#   && sudo apt-get install -y python3.10\
#   && sudo apt-get install -y python3.10-venv
# RUN sudo apt-get install python3-pip -yq\
#   && python3.10 -m pip install --upgrade pip
# RUN sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 100

# # FROM therest AS python311
# RUN sudo add-apt-repository ppa:deadsnakes/ppa -y\
#   && sudo apt-get install -y python3.11\
#   && sudo apt-get install -y python3.11-venv
# RUN sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 110
# RUN sudo apt-get install python3-pip -yq\
#   && python3.11 -m pip install --upgrade pip\
#   && python3.11 -m ensurepip --upgrade

RUN sudo apt-get update && sudo apt-get upgrade -y\
  && sudo add-apt-repository ppa:deadsnakes/ppa -y\
  && sudo apt-get update\
  && sudo apt-get install -y\
    python3.12\
    python3.12-venv
RUN sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 120
RUN curl -sSL https://bootstrap.pypa.io/get-pip.py | python3 -
ENV PATH="${USERHOME}/.local/bin:${PATH}"
# RUN sudo apt install -y\
#     python3-pip
# RUN python3.12 -m pip install --upgrade pip\
#   && python3.12 -m ensurepip --upgrade

RUN sudo apt-get install -y postgresql-client\
  && sudo apt-get install -y\
    inetutils-tools\
    dnsutils\
    traceroute\
    bind9-host\
    locales\
    zip\
    bsdmainutils\
    ntpdate\
    tree\
    binutils   


RUN cat >>$USERHOME/.bashrc <<EOF
echo -e "use \e[3msudo update-alternatives --set python3 [PATH]\e[0m] to change python"
echo -e "\\tusing: \$(openssl version)"
echo -e "\\tusing: \$(python --version)"
echo -e "\\tusing: \$(pip --version)"
sudo update-alternatives --list python3
EOF

RUN cat >$USERHOME/bin/pyenv <<EOF
(
function pyenv {
if [ -z "\$1" ];then echo need env name && return 2;fi
env=.\${1%/}-\$(python --version | tr '[:upper:]' '[:lower:]' | sed 's/python//' | sed 's/\ //').nogit
if [ -d \$env ];then echo . ./\$env/bin/activate && return 0;fi
python -m venv \$env
echo '. ~/.bashrc' >>./\$env/bin/activate
echo 'which python' >>./\$env/bin/activate
echo 'which pip' >>./\$env/bin/activate
echo . ./\$env/bin/activate
}
pyenv \$1
)
EOF
RUN sudo chmod u+x $USERHOME/bin/pyenv

################# MIDDLE ##################


# RUN cat >>$USERHOME/.bashrc <<EOF
# echo "[user]
#   name = \"\$gitname\"
#   email = \$gituser
# [ssh]
#   identity = \$gitkey
# [safe]
# 	directory = /home/developer/devnet/appdev"\
#   >~/.gitconfig
# EOF
# RUN echo "\
# [user]\n\
#   name = \n\
#   email = \n\
# [ssh]\n\
#   identity = \n\
# " >>$USERHOME/.gitconfig
# RUN echo "\
# [user]\n\
#   name = \n\
#   email = \n\
# [ssh]\n\
#   identity = \n\
# # " >>$USERHOME/.bashrc
# RUN cat >>$USERHOME/.bashrc <<EOF
# git config --global --add user.name "\$gitname"
# git config --global --add user.email \$gituser
# git config --global --add ssh.identity \$gitkey
# EOF

RUN cat >>$USERHOME/.bashrc <<EOF
git config --global user.name "\$gitname"
git config --global user.email \$gituser
git config --global ssh.identity \$gitkey
git config --global core.autocrlf input
git config --global core.longpaths true
function printenv {   command printenv "\$@" | sort -t= -k1,1 | sed -E 's/^([^=]+)=/\x1b[0;33m\1\x1b[0m=/'; }
EOF

RUN cat >$USERHOME/bin/audit_env <<EOF
#!/bin/bash
unset AUDIT_FLAG
unset NON_COMPLIANT_FLAG

function run_audit {
local DIR=\${1:-./}
echo Searching in \$DIR
find \$DIR \
  -path "*/.git" -prune -o \
  -path "*/.vscode-server" -prune -o \
  -path "*/node_modules" -prune -o \
  -type f \( -name ".env*" -o -name "*.properties" \) -exec /bin/ls -l {} +
}
function find_env {
local DIR=\${1:-./}
find \$DIR \
  -path "*/.git" -prune -o \
  -path "*/.vscode-server" -prune -o \
  -path "*/node_modules" -prune -o \
  -type f \( -name ".env*" -o -name "*.properties" \) -print
}
function set_non_compliant {
local DIR=\${1:-./}
find "\$DIR" \
  -path "*/.git" -prune -o \
  -path "*/.vscode-server" -prune -o \
  -path "*/node_modules" -prune -o \
  -type f \( -name ".env*" -o -name "*.properties" \) \
  -exec sh -c '
    for f; do
      # Get current octal permissions
      # Try GNU stat first, then BSD
      perms=\$(stat -c "%a" "\$f" 2>/dev/null || stat -f "%Lp" "\$f")
      if [ "\$perms" != "400" ]; then
        chmod 400 "\$f"
        echo "Updated: \$f" && /bin/ls -Al \$f
      fi
    done
  ' sh {} +
}
function set_permission {
local DIR=\${1:-./}
find \$DIR \
  -path "*/.git" -prune -o \
  -path "*/.vscode-server" -prune -o \
  -path "*/node_modules" -prune -o \
  -type f \( -name ".env*" -o -name "*.properties" \) -exec chmod 400 {} +
}

for i in "\$@"
do
case \$i in
--help|-h)
  shift
  echo -e Usage: "\$(basename \$BASH_SOURCE) <OPTION> [DIR]
\t -h\t help
\t -l\t list all
\t -f\t find all
\t -x\t chmod 400 all
\t -X\t chmod 400 non compliant
  "
  exit 0
  ;;
-l)
  shift
  run_audit \$@;
  exit \$?
  ;;
-f)
  shift
  find_env \$@;
  exit \$?
  ;;
-x)
  shift
  AUDIT_FLAG=1
  set_permission \$@;
  exit \$?
  ;;
-X)
  shift
  NON_COMPLIANT_FLAG=1
  set_non_compliant \$@;
  exit \$?
  ;;
esac
done

# No args, call for help
. \$BASH_SOURCE -h

EOF
RUN sudo chmod u+x $USERHOME/bin/audit_env
#######################################################
######## BETTER NOT TO CHANGE MUCH BELOW HERE #########
#######################################################

################# BOTTOM ##################

# RUN cat >~/bin/countdown.sh <<EOF
# function countdown {
#   local max=\${1:-10}
#   local min=0
#   local msg=\${2:-}
#   # validate integers
#   if ! [[ "\$max" =~ ^[0-9]+\$ ]] || ! [[ "\$min" =~ ^[0-9]+\$ ]]; then
#     printf 'Usage: countdown MAX [MIN] [MESSAGE]\n'
#     return 2
#   fi
#   if (( min >= max )); then
#     printf 'Error: MIN (%d) must be less than MAX (%d)\n' "\$min" "\$max"
#     return 2
#   fi
#   for ((i = max; i > min; i--)); do
#     if [ -n "\$msg" ]; then
#       printf '\r   %s in %d... ' "\$msg" "\$i"
#     else
#       printf '\r   in %d... ' "\$i"
#     fi
#     sleep 1
#   done
# }

# EOF

# FROM base AS end
COPY assets.docker/git-prompt.sh $USERHOME/git-prompt.sh
RUN cat >>$USERHOME/.bashrc <<EOF
function awswho { aws sts get-caller-identity; }
alias docker="sudo docker"
. $USERHOME/appdev/bashrc-hook.sh
EOF

# vimrc colo values: slate | pablo | murphy
RUN cat >~/.vimrc <<EOF
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab autoindent
set number
set nocompatible
syntax on
colo pablo
set cursorline
set hls
hi CursorLine   cterm=NONE ctermbg=NONE ctermfg=NONE
hi CursorLineNr   cterm=NONE ctermbg=36 ctermfg=NONE
EOF
RUN cat >>$USERHOME/.bashrc <<EOF
. ~/git-prompt.sh
function set_ps1 {
PS1_ON="\[\033[0m\]on"
PS1_COLON="\[\033[0m\]:"
PS1_HOST="\[\033[0;34m\]\h"
PS1_BRACKET_o="\[\033[0;35m\]["
PS1_BRACKET_c="\[\033[0;35m\]]"
PS1_at="\[\033[0m\]@\[\033[0m\]"

PS1_DATE="\[\033[0;31m\]\\\`date +%Y-%m-%d\\\` \[\033[1;31m\]\\\`date +%H:%M:%S\\\`"
PS1_GITSSH="\[\033[0;36m\]\\\`basename \\\$(git config --get-regexp "ssh.identity"|tail -1|awk '{ print \\\$2 }') 2>/dev/null\\\`"
PS1_GITUSER="\[\033[0;36m\]\\\`git config --get-regexp \"user.email\"|tail -1|sed \"s/user\.email//\"\\\`"
PS1_BRANCH="\[\033[0;35m\](\\\$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo not-a-repo))"
PS1_OS="\[\033[3;34m\]\$(grep -iE ^ID= /etc/os-release 2>/dev/null|awk -F= '{print \$2}'|awk '{print \$1}')"
PS1_USER="\[\033[3;34m\]\u\[\033[0m\]"
PS1_HOST="\[\033[3;34m\]\h\[\033[0m\]"
PS1_PWD="\[\033[1;33m\]\w\[\033[0m\]"

PS1_REPO="check-ps1-repo-in-dot-bashrc"
PS1_REPO="\[\033[1;36m\]\\\`git remote -v|head -1 2>/dev/null|awk '{print \\\$2}'\\\`"

PS1_GITLINE="\${PS1_GITSSH}\${PS1_COLON} \${PS1_REPO}"
PS1_USERATHOST="\${PS1_USER}\${PS1_at}\${PS1_HOST} \${PS1_BRANCH}"
PS1_ENV="\[\033[3;32m\]\\\`echo \\\$sdenv\\\`"
PS1_RM="\[\033[0;31m\]\${__RM__}"
ps1=
ps1+="\n\${PS1_USERATHOST}"
ps1+="\n\${PS1_GITLINE}"
ps1+="\n\${PS1_DATE} \${PS1_ENV}\[\033[0;32m\]\\\${VIRTUAL_ENV_PROMPT}\${PS1_BRACKET_o}\${PS1_PWD}\${PS1_BRACKET_c}"
ps1+="\n\${PS1_RM} \[\033[1;33m\]\W/\[\033[0;32m\]$ \[\033[0m\]"
echo \$ps1
}
export PS1="\$(set_ps1)"
EOF

# RUN cat >~/.sqliterc <<EOF
# .headers on
# .mode column
# .nullvalue NULL
# EOF

############ CONNECT ENTRYPOINT W/ VOLUME #############
RUN cat >/tmp/entrypoint.sh <<EOF
#!/bin/bash
set -euo pipefail
echo "Setting ownership of \${VOL_MNT} to \$(id -u):\$(id -g)"
sudo chown -R \$(id -u):\$(id -g) "\${VOL_MNT}"
if [ \$# -eq 0 ]; then
  exec bash
else
  exec "\$@"
fi
EOF
RUN sudo mv /tmp/entrypoint.sh /entrypoint.sh\
  && sudo chmod +x /entrypoint.sh
#######################################################

RUN sudo apt-get clean
RUN sudo rm -rf /var/lib/apt/lists/*
ARG BUILD_DATE
LABEL build-date=${BUILD_DATE}
RUN echo 'function rand { local n=${1:-8}; base64 </dev/urandom | tr -dc "A-Za-z0-9" | head -c $n; }\n\
echo -e "user:base ('${BUILD_DATE}')"\n\
'>>$USERHOME/.bashrc

RUN sudo apt-get update -qq\
  && sudo apt-get install -y locales

RUN sudo locale-gen en_US.UTF-8\
  && sudo update-locale LANG=en_US.UTF-8\
  && DEBIAN_FRONTEND=noninteractive TZ=UTC\
  sudo apt-get install -y --no-install-recommends\
    tzdata\
  && sudo ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime\
  && sudo dpkg-reconfigure --frontend noninteractive tzdata


# RUN DEBIAN_FRONTEND=noninteractive TZ=America/Chicago\
#   sudo apt-get install -y --no-install-recommends\
#     tzdata\
#   && sudo ln -fs /usr/share/zoneinfo/US/Central /etc/localtime\
#   && sudo dpkg-reconfigure --frontend noninteractive tzdata

# RUN sudo apt-get install -y\
#   netcat-traditional



# # RUN sudo apt-get clean\
# #   && sudo rm -rf /var/lib/apt/lists/*


# # VOLUME ["/var/run/docker.sock"]
# # VOLUME ["/var/lib/docker"]
